const char *get_csv_field (char *, int);
void opcion_1(List *L);
void opcion_3(List *L);
void opcion_4(List *L);
void opcion_5(char *marca, List* L);
void opcion_6(char* nombre, List* L);
void opcion_7(char* genero, List* L);
void opcion_8(char* genero,int jugadores, List* L);
void opcion_9(List *L);
void opcion_10(List *L);